# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Logstash Service

apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: wazuh
  labels:
    app: wazuh-logstash
spec:
  selector:
    app: wazuh-logstash
  ports:
    - name: beats
      port: 5000
      targetPort: 5000
